### ISSUE TITLE
Error when conditional blocks are not within a layer

### ISSUE THREAD

**Issue by lbraun** [ebrelsford/cartocss2json#1]
Hi @ebrelsford, I am getting the following error when I try to run cartocss2json:

```bash
$ cartocss2json < sample_cartocss.txt 
/usr/local/lib/node_modules/cartocss2json/index.js:42
        return rule.elements[0].clean;
                                ^

TypeError: Cannot read property 'clean' of undefined
    at /usr/local/lib/node_modules/cartocss2json/index.js:42:33
    at Array.map (<anonymous>)
    at parse (/usr/local/lib/node_modules/cartocss2json/index.js:41:27)
    at cartocss2json (/usr/local/lib/node_modules/cartocss2json/index.js:30:16)
    at /usr/local/lib/node_modules/cartocss2json/bin/cartocss2json.js:14:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

Here is the contents of sample_cartocss.txt:

```
#layer {polygon-opacity: 1; line-width: 0.5; line-color: #FFF; line-opacity: 1;}[value >= 0.9][value < 2]{polygon-fill:#b10026;} [value >= 0.8][value < 0.9]{polygon-fill:#e31a1c;} [value >= 0.7][value < 0.8]{polygon-fill:#fc4e2a;} [value >= 0.6][value < 0.7]{polygon-fill:#fd8d3c;}[value >= 0.5][value < 0.6]{polygon-fill:#feb24c;} [value >= 0.4][value < 0.5]{polygon-fill:#fed976;}[value >= 0.0001][value < 0.4]{polygon-fill:#ffffb2;} [value >= 0][value < 0.0001]{polygon-fill:#bdbdbd;}
```

Perhaps you aren't maintaining this package anymore, but I thought it was worth asking if you knew a quick solution. Thanks!

**Comment by ebrelsford** [comment]
This package is not very complete or robust.

Right now you have a number of conditional statements in the CartoCSS that, while they parse, don't actually do anything:

```css
#layer {
    polygon-opacity: 1;
    line-width: 0.5;
    line-color: #FFF;
    line-opacity: 1;
}
[value >= 0.9][value < 2]{
    polygon-fill:#b10026;
}
[value >= 0.8][value < 0.9]{
    polygon-fill:#e31a1c;
}
[value >= 0.7][value < 0.8]{
    polygon-fill:#fc4e2a;
}
[value >= 0.6][value < 0.7]{
    polygon-fill:#fd8d3c;
}
[value >= 0.5][value < 0.6]{
    polygon-fill:#feb24c;
}
[value >= 0.4][value < 0.5]{
    polygon-fill:#fed976;
}
[value >= 0.0001][value < 0.4]{
    polygon-fill:#ffffb2;
}
[value >= 0][value < 0.0001]{
    polygon-fill:#bdbdbd;
}
```

If you put all of these inside of the `#layer` group like this, the script works:

```css
#layer {
    polygon-opacity: 1;
    line-width: 0.5;
    line-color: #FFF;
    line-opacity: 1;

    [value >= 0.9][value < 2]{
        polygon-fill:#b10026;
    }
    [value >= 0.8][value < 0.9]{
        polygon-fill:#e31a1c;
    }
    [value >= 0.7][value < 0.8]{
        polygon-fill:#fc4e2a;
    }
    [value >= 0.6][value < 0.7]{
        polygon-fill:#fd8d3c;
    }
    [value >= 0.5][value < 0.6]{
        polygon-fill:#feb24c;
    }
    [value >= 0.4][value < 0.5]{
        polygon-fill:#fed976;
    }
    [value >= 0.0001][value < 0.4]{
        polygon-fill:#ffffb2;
    }
    [value >= 0][value < 0.0001]{
        polygon-fill:#bdbdbd;
    }
}
```

But dealing with conditional blocks like these doesn't actually do much right now, so that's probably not going to be too satisfying.
